# Generated by Django 6.0.1 on 2026-01-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='residencial',
            name='dias_maximos_anticipacion',
            field=models.IntegerField(default=30, help_text='Días máximos de futuro permitidos'),
        ),
        migrations.AddField(
            model_name='residencial',
            name='dias_minimos_anticipacion',
            field=models.IntegerField(default=7, help_text='Días mínimos antes de la reserva'),
        ),
        migrations.AddField(
            model_name='residencial',
            name='duracion_maxima_horas',
            field=models.IntegerField(default=5, help_text='Horas máximas permitidas por evento'),
        ),
        migrations.CreateModel(
            name='BloqueoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(help_text='Ej: Mantenimiento Piscina, Viernes Santo', max_length=100)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
            ],
            options={
                'unique_together': {('residencial', 'fecha')},
            },
        ),
    ]
