# Generated by Django 6.0.1 on 2026-01-30 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva_hora_fin_reserva_hora_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CUOTA', 'Cuota de Mantenimiento'), ('GAS', 'Consumo de Gas'), ('EXTRA', 'Cuota Extraordinaria')], default='CUOTA', max_length=10)),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Carga de Gas Enero', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('categoria', models.CharField(choices=[('GAS', 'Compra de Gas (Camión)'), ('SERVICIOS', 'Servicios Básicos (Luz, Agua)'), ('MANTENIMIENTO', 'Mantenimiento y Reparaciones'), ('NOMINA', 'Nómina y Personal'), ('OTRO', 'Otros')], default='OTRO', max_length=20)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
            ],
        ),
        migrations.CreateModel(
            name='LecturaGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateField(default=django.utils.timezone.now)),
                ('lectura_anterior', models.DecimalField(decimal_places=2, help_text='En m3', max_digits=10)),
                ('lectura_actual', models.DecimalField(decimal_places=2, help_text='En m3', max_digits=10)),
                ('precio_galon_mes', models.DecimalField(decimal_places=2, help_text='Precio al que compraste el galón este mes', max_digits=6)),
                ('factor_conversion', models.DecimalField(decimal_places=2, default=1.2, help_text='Factor para convertir m3 a galones', max_digits=5)),
                ('consumo_galones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento')),
                ('factura_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.factura')),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
            ],
        ),
    ]
