# Generated by Django 6.0.1 on 2026-01-31 01:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_factura_gasto_lecturagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cuota mensual de mantenimiento', max_digits=10),
        ),
        migrations.AddField(
            model_name='residencial',
            name='dia_corte',
            field=models.IntegerField(default=1, help_text='Día del mes para generar cuotas'),
        ),
        migrations.AddField(
            model_name='residencial',
            name='dias_gracia',
            field=models.IntegerField(default=15, help_text='Días después del corte para pagar sin mora'),
        ),
        migrations.AddField(
            model_name='residencial',
            name='porcentaje_mora',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='% de Recargo por mora', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bloqueofecha',
            name='motivo',
            field=models.CharField(help_text='Ej: Mantenimiento Piscina', max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturagas',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='lecturagas',
            name='lectura_actual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lecturagas',
            name='lectura_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lecturagas',
            name='precio_galon_mes',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
