# Generated by Django 6.0.1 on 2026-01-31 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apartamento_monto_cuota_residencial_dia_corte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del anuncio', max_length=100)),
                ('mensaje', models.TextField(help_text='Detalle de la noticia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
            ],
        ),
    ]
