# Generated by Django 6.0.1 on 2026-02-04 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('estado', models.CharField(choices=[('PENDIENTE', '🔴 Pendiente'), ('EN_PROCESO', '🟠 En Proceso'), ('RESUELTO', '🟢 Resuelto'), ('RECHAZADO', '⚪ Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario_admin', models.TextField(blank=True, help_text='Respuesta de la administración', null=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
