# Generated by Django 6.0.1 on 2026-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factura_monto_pagado_usuario_saldo_a_favor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
