# Generated by Django 6.0.1 on 2026-02-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_factura_saldo_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='mora_aplicada',
            field=models.BooleanField(default=False, help_text='Indica si ya se le aplicó el recargo por mora'),
        ),
    ]
