# Generated by Django 6.0.1 on 2026-02-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_factura_mora_aplicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='mora_aplicada',
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_ultima_mora',
            field=models.DateField(blank=True, help_text='Fecha de la última aplicación de mora', null=True),
        ),
    ]
