# Generated by Django 6.0.1 on 2026-02-13 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_factura_mora_aplicada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
