# Generated by Django 6.0.1 on 2026-02-15 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_factura_fecha_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('nota_usuario', models.TextField(blank=True, help_text='Ej: Pago de Marzo y Abril', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
