# Generated by Django 6.0.1 on 2026-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reportepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencial',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Dinero en banco antes de usar el sistema', max_digits=12),
        ),
    ]
