# Generated by Django 6.0.1 on 2026-02-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_residencial_saldo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturagas',
            name='lectura_actual',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lecturagas',
            name='lectura_anterior',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
