# Generated by Django 6.0.1 on 2026-02-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_lecturagas_lectura_actual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='saldo_a_favor',
            new_name='saldo_favor_gas',
        ),
        migrations.AddField(
            model_name='reportepago',
            name='tipo_pago',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Cuota / Mantenimiento'), ('GAS', 'Consumo de Gas'), ('OTRO', 'Otro')], default='MANTENIMIENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo_favor_mantenimiento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
