# Generated by Django 6.0.1 on 2026-03-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_saldo_a_favor_usuario_saldo_favor_gas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoExtraordinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CONTROL', 'Venta de Control/Token'), ('BBQ', 'Uso de Gas BBQ'), ('MULTA', 'Multa / Sanción'), ('DANOS', 'Cobro por Daños (Sillas/Áreas)'), ('OTROS', 'Otros Ingresos')], default='OTROS', max_length=20)),
                ('concepto_detalle', models.CharField(help_text='Ej: Control portón negro - Apto 302', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('comprobante', models.CharField(blank=True, help_text='No. de recibo físico', max_length=50, null=True)),
                ('Apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento', verbose_name='Apartamento/Unidad')),
            ],
        ),
    ]
