# Generated by Django 6.0.1 on 2026-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ingresoextraordinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencial',
            name='bloquear_morosos',
            field=models.BooleanField(default=False, help_text='Si se activa, los usuarios con cuotas vencidas no podrán crear reservas.', verbose_name='Bloquear reservas a morosos'),
        ),
    ]
