# Generated by Django 6.0.1 on 2026-03-19 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_residencial_bloquear_morosos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.TextField()),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia/Modificación'), ('DANGER', 'Crítico/Eliminación')], default='INFO', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
                ('usuario', models.ForeignKey(blank=True, help_text='Quién hizo la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
