# Generated by Django 5.2.10 on 2026-05-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Plan Básico, Plan Premium', max_length=50)),
                ('precio_por_apartamento', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('precio_usuario_extra', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('dias_prueba_default', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Soporte Premium 24/7, Módulo Contable Avanzado', max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='areasocial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloqueofecha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingresoextraordinario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturagas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportepago',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='residencial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador (Todo el sistema)'), ('ADMIN_RESIDENCIAL', 'Administrador de Residencial'), ('ASISTENTE', 'Asistente Administrativo'), ('RESIDENTE', 'Residente')], default='RESIDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='SuscripcionResidencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRUEBA', 'Período de Prueba (Trial)'), ('ACTIVA', 'Suscripción Activa'), ('SUSPENDIDA', 'Cuenta Suspendida (Morosidad)'), ('CANCELADA', 'Cuenta Cancelada')], default='PRUEBA', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.plansuscripcion')),
                ('residencial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='core.residencial')),
                ('servicios_adicionales', models.ManyToManyField(blank=True, to='core.servicioadicional')),
            ],
        ),
    ]
