# Generated by Django 5.2.10 on 2026-05-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_plansuscripcion_servicioadicional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSaaS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej: Mensualidad SaaS - Mayo 2026', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_saas', to='core.residencial')),
                ('suscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suscripcionresidencial')),
            ],
        ),
    ]
