# Generated by Django 5.2.10 on 2026-05-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_facturasaas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('COMPRAS_GAS', 'Compras Gas (Camión)'), ('COMPRAS_GENERALES', 'Compras Generales (Insumos, limpieza, etc.)'), ('SERV_ELECTRICIDAD', 'Servicios: Electricidad'), ('SERV_AGUA', 'Servicios: Agua'), ('SERV_INTERNET', 'Servicios: Teléfono e Internet'), ('SERV_AYUNTAMIENTO', 'Servicios: Ayuntamiento (Recogida de basura/tasas)'), ('MANT_GENERAL', 'Mantenimiento y Reparaciones Generales'), ('MANT_PISCINA', 'Mantenimiento de Piscina'), ('MANT_ASCENSORES', 'Mantenimiento de Ascensores'), ('JARDINERIA', 'Jardinería y Áreas Verdes'), ('FUMIGACION', 'Fumigación y Control de Plagas'), ('NOMINA', 'Nómina y Personal (Conserjes, seguridad, etc.)'), ('HONORARIOS_PROF', 'Honorarios Profesionales (Contables, legales)'), ('SEGUROS', 'Seguros (Pólizas del edificio)'), ('IMPUESTOS', 'Impuestos'), ('DONACIONES', 'Donaciones'), ('IMPREVISTOS', 'Imprevistos y Caja Chica')], default='IMPREVISTOS', max_length=50),
        ),
    ]
