# Generated by Django 5.2.10 on 2026-05-13 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_gasto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Muebles, Vehículos, Servicios', max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de FontAwesome (ej: fas fa-couch)', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENDIDO', 'Vendido'), ('INACTIVO', 'Inactivo (Pausado)')], default='ACTIVO', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriamarketplace')),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencial')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_marketplace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
