# Generated by Django 5.2.10 on 2026-05-14 00:41

from django.db import migrations

def crear_categorias(apps, schema_editor):
    CategoriaMarketplace = apps.get_model('core', 'CategoriaMarketplace')
    
    categorias = [
        ('Muebles y Hogar', 'fas fa-couch'),
        ('Vehículos y Repuestos', 'fas fa-car'),
        ('Electrónica', 'fas fa-laptop'),
        ('Servicios y Mantenimiento', 'fas fa-tools'),
        ('Moda y Accesorios', 'fas fa-tshirt'),
        ('Artículos para Bebés', 'fas fa-baby-carriage'),
        ('Controles y Tokens', 'fas fa-key'),
        ('Otros', 'fas fa-box')
    ]
    
    for nombre, icono in categorias:
        CategoriaMarketplace.objects.get_or_create(nombre=nombre, defaults={'icono': icono})

def revertir_categorias(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_categoriamarketplace_productomarketplace'),
    ]

    operations = [
        migrations.RunPython(crear_categorias, revertir_categorias),
    ]
