# Generated by Django 5.2.10 on 2026-05-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_categorias_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomarketplace',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productomarketplace',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('VENDIDO', 'Vendido'), ('INACTIVO', 'Inactivo (Pausado)'), ('VENCIDO', 'Vencido (Expirado)')], default='ACTIVO', max_length=20),
        ),
    ]
