# Generated by Django 5.2.10 on 2026-05-14 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_expiracion_anuncios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cedula', models.CharField(blank=True, help_text='Cédula o Pasaporte', max_length=20, null=True)),
                ('cargo', models.CharField(choices=[('CONSERJE', 'Conserje'), ('SEGURIDAD', 'Seguridad / Vigilante'), ('JARDINERO', 'Jardinero'), ('MANTENIMIENTO', 'Mantenimiento General'), ('ADMINISTRATIVO', 'Administrativo'), ('OTRO', 'Otro')], default='CONSERJE', max_length=50)),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Salario mensual base', max_digits=10)),
                ('fecha_contratacion', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.residencial')),
            ],
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.CharField(help_text='Ej: Mayo 2026', max_length=50)),
                ('salario_base_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('concepto_extra', models.CharField(blank=True, help_text='Ej: Bono por limpieza profunda', max_length=200, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.empleado')),
                ('gasto_asociado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_nomina_origen', to='core.gasto')),
            ],
        ),
    ]
