# Generated by Django 5.2.10 on 2026-05-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_modulo_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagonomina',
            name='tipo_pago',
            field=models.CharField(choices=[('MENSUAL', 'Mensual (100% Salario)'), ('QUINCENAL', 'Quincena (50% Salario)')], default='MENSUAL', max_length=20),
        ),
    ]
