# Generated by Django 5.2.10 on 2026-05-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pago_quincenal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagonomina',
            name='tipo_pago',
            field=models.CharField(choices=[('MENSUAL', 'Mensual (100% Salario)'), ('QUINCENAL', 'Quincena (50% Salario)'), ('DOBLE_SUELDO', 'Doble Sueldo / Regalía (100% Salario)')], default='MENSUAL', max_length=20),
        ),
    ]
