# Generated by Django 5.2.10 on 2026-05-18 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_doble_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='precio_modulo_seguridad',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Precio extra por el módulo de seguridad', max_digits=8),
        ),
        migrations.AddField(
            model_name='residencial',
            name='modulo_seguridad_activo',
            field=models.BooleanField(default=False, help_text='Activa el control de visitas y garita virtual'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador (Todo el sistema)'), ('ADMIN_RESIDENCIAL', 'Administrador de Residencial'), ('ASISTENTE', 'Asistente Administrativo'), ('SEGURIDAD', 'Personal de Seguridad / Recepción'), ('RESIDENTE', 'Residente')], default='RESIDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=150)),
                ('cedula_visitante', models.CharField(blank=True, max_length=50, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_esperada', models.DateField()),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ESPERADA', 'Esperada'), ('EN_CURSO', 'En Curso (Dentro)'), ('FINALIZADA', 'Finalizada (Salió)'), ('CANCELADA', 'Cancelada')], default='ESPERADA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_esperadas', to='core.apartamento')),
                ('reserva_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='core.reserva')),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.residencial')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_visitas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
