# Generated by Django 5.2.10 on 2026-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_plansuscripcion_precio_modulo_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturagas',
            name='consumo_galones',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
