# Generated by Django 5.2.10 on 2026-06-03 01:18

import django.db.models.deletion
from django.db import migrations, models


def populate_default_categories(apps, schema_editor):
    Residencial = apps.get_model('core', 'Residencial')
    Categoria = apps.get_model('core', 'Categoria')
    
    CATEGORIAS_GASTO_DEFAULT = [
        ('COMPRAS_GAS', 'Compras Gas (Camión)'),
        ('COMPRAS_GENERALES', 'Compras Generales (Insumos, limpieza, etc.)'),
        ('SERV_ELECTRICIDAD', 'Servicios: Electricidad'),
        ('SERV_AGUA', 'Servicios: Agua'),
        ('SERV_INTERNET', 'Servicios: Teléfono e Internet'),
        ('SERV_AYUNTAMIENTO', 'Servicios: Ayuntamiento (Recogida de basura/tasas)'),
        ('MANT_GENERAL', 'Mantenimiento y Reparaciones Generales'),
        ('MANT_PISCINA', 'Mantenimiento de Piscina'),
        ('MANT_ASCENSORES', 'Mantenimiento de Ascensores'),
        ('JARDINERIA', 'Jardinería y Áreas Verdes'),
        ('FUMIGACION', 'Fumigación y Control de Plagas'),
        ('NOMINA', 'Nómina y Personal (Conserjes, seguridad, etc.)'),
        ('HONORARIOS_PROF', 'Honorarios Profesionales (Contables, legales)'),
        ('SEGUROS', 'Seguros (Pólizas del edificio)'),
        ('IMPUESTOS', 'Impuestos'),
        ('DONACIONES', 'Donaciones'),
        ('IMPREVISTOS', 'Imprevistos y Caja Chica'),
    ]
    
    CATEGORIAS_INGRESO_DEFAULT = [
        ('CONTROL', 'Venta de Control/Token'),
        ('BBQ', 'Uso de Gas BBQ'),
        ('MULTA', 'Multa / Sanción'),
        ('DANOS', 'Cobro por Daños (Sillas/Áreas)'),
        ('OTROS', 'Otros Ingresos'),
    ]
    
    for r in Residencial.objects.all():
        for codigo, nombre in CATEGORIAS_GASTO_DEFAULT:
            Categoria.objects.get_or_create(
                residencial=r,
                codigo=codigo,
                tipo='GASTO',
                defaults={'nombre': nombre, 'activo': True}
            )
        for codigo, nombre in CATEGORIAS_INGRESO_DEFAULT:
            Categoria.objects.get_or_create(
                residencial=r,
                codigo=codigo,
                tipo='INGRESO',
                defaults={'nombre': nombre, 'activo': True}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_lecturagas_consumo_galones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('GASTO', 'Gasto'), ('INGRESO', 'Ingreso')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.residencial')),
            ],
            options={
                'unique_together': {('residencial', 'nombre', 'tipo')},
            },
        ),
        migrations.RunPython(populate_default_categories, reverse_code=migrations.RunPython.noop),
    ]
