# Generated by Django 5.2.10 on 2026-10-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='concepto',
            field=models.CharField(max_length=255),
        ),
    ]
